apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  steps:
    - name: npm-install
      image: node:18
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  steps:
    - name: run-tests
      image: node:18
      script: |
        npm test
